import { StyleSheet } from "react-native";

export const styles_button = StyleSheet.create({
    button_red: {
        alignItems: 'center',
        borderRadius: 50,
        borderWidth: 2,
        borderColor: 'red',
        width: '25%',
        height: 30,
        marginVertical: 3,
        justifyContent: 'center',
    },
    button_green: {
        alignItems: 'center',
        borderRadius: 50,
        borderWidth: 2,
        borderColor: '#03C04A',
        width: '25%',
        height: 30,
        marginVertical: 3,
        justifyContent: 'center',
    },
    button_green_active: {
        alignItems: 'center',
        borderRadius: 50,
        borderWidth: 2,
        borderColor: '#03C04A',
        width: '25%',
        height: 30,
        justifyContent: 'center',
        marginVertical: 3,
        backgroundColor: '#03C04A',
    },
    button_purple: {
        alignItems: 'center',
        borderRadius: 50,
        borderWidth: 2,
        borderColor: '#E39FF6',
        width: '45%',
        height: 30,
        justifyContent: 'center',
        marginVertical: 3,
    },
    button_purple_active: {
        alignItems: 'center',
        borderRadius: 50,
        borderWidth: 2,
        borderColor: '#9867C5',
        width: '45%',
        height: 30,
        justifyContent: 'center',
        marginVertical: 3,
        backgroundColor: '#9867C5',
    },
    button_blue: {
        alignItems: 'center',
        borderRadius: 50,
        borderWidth: 2,
        borderColor: '#8080FF',
        width: '45%',
        height: 30,
        justifyContent: 'center',
        marginVertical: 3,
    },
    button_blue_active: {
        alignItems: 'center',
        borderRadius: 50,
        borderWidth: 2,
        borderColor: '#8080FF',
        width: '45%',
        height: 30,
        justifyContent: 'center',
        marginVertical: 3,
        backgroundColor: '#8080FF',
    },
});
